#!/bin/bash

# Output folder where weights file is saved is eiher pulled from ./run_components.sh 
# OR set via commandline if this script is run directly
if [[ -v FOLDER ]]; then
	echo pulling FOLDER from calling script: $FOLDER
else
	FOLDER=$1	# take from commandline if not set
fi

if [[ -v MODEL ]]; then
	echo pulling MODEL from calling script: $MODEL
else
	MODEL=$2	# take from commandline if not set
fi

if [[ -v TENSORFLOW_FILE ]]; then
	echo pulling TENSORFLOW_FILE from calling script: $TENSORFLOW_FILE
else
	TENSORFLOW_FILE=$3	# take from commandline if not set
fi

#PATH_BAK=$PATH
#export PATH=$PATH:/home/chethana/anaconda2/bin
#eval "$(conda shell.bash hook)"
. ~/anaconda3/bin/activate
conda activate tensorflow
python $TENSORFLOW_FILE -d $FOLDER -m $MODEL
conda deactivate
sed -i -e "s/\\[/ /g" ../$FOLDER/$MODEL/weights_ba.txt
sed -i -e "s/\\]/ /g" ../$FOLDER/$MODEL/weights_ba.txt
sed -i -e "s/\\,/ /g" ../$FOLDER/$MODEL/weights_ba.txt
#PATH=$PATH_BAK



